name: .NET Framework Build (Windows)

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Windows runner required for .NET Framework

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install .NET Framework 4.8.1 Developer Pack
      - name: Install .NET Framework 4.8.1
        run: |
          choco install dotnetfx --version=4.8.1 -y --no-progress
          refreshenv

      # Optional: Install MSBuild tools if needed
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Restore NuGet packages
      - name: Restore dependencies
        run: msbuild ST10449143_PROGPOEPART3/ST10449143_PROGPOEPART3.sln /t:Restore /p:Configuration=Release

      # Build the solution
      - name: Build solution
        run: msbuild ST10449143_PROGPOEPART3/ST10449143_PROGPOEPART3.sln /p:Configuration=Release /p:Platform="Any CPU"

      # Optional: Run tests if you have them
      - name: Run tests
        run: |
          cd ST10449143_PROGPOEPART3
          vstest.console bin\Release\*.Test.dll  # Adjust if you have test projects
        continue-on-error: true
