name: .NET Framework 4.8.1 Build (Windows)

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Download and install .NET Framework 4.8.1 Developer Pack
      - name: Install .NET Framework 4.8.1
        run: |
          $url = "https://download.visualstudio.microsoft.com/download/pr/2d6bb6b2-226a-4baa-bdec-798822606ff1/8494001c276a4b96804cde7829c04d7f/ndp481-web.exe"
          $installer = "$env:TEMP\ndp481.exe"
          Invoke-WebRequest -Uri $url -OutFile $installer
          Start-Process -FilePath $installer -ArgumentList "/q /norestart" -Wait -NoNewWindow
          Remove-Item $installer

      # Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Restore and Build
      - name: Restore and Build
        run: |
          msbuild ST10449143_PROGPOEPART3/ST10449143_PROGPOEPART3.sln `
            /t:Restore `
            /p:Configuration=Release `
            /p:Platform="Any CPU" `
            /p:RestorePackagesConfig=true

          msbuild ST10449143_PROGPOEPART3/ST10449143_PROGPOEPART3.sln `
            /p:Configuration=Release `
            /p:Platform="Any CPU"

      # Optional: Run tests
      - name: Run tests
        run: |
          cd ST10449143_PROGPOEPART3
          vstest.console bin\Release\*.Test.dll
        continue-on-error: true
